name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - dask-core
  - distributed
  - numcodecs
  - pyarrow
  - pytest
  - requests
  - setuptools-scm
  - s3fs
  - xarray
  - zarr>=2.11.0
