name: ZCollection
channels:
  - conda-forge
  - defaults
dependencies:
  - dask-core
  - distributed
  - furo
  - numcodecs
  - pyarrow
  - pypandoc
  - pytest
  - requests
  - s3fs
  - setuptools-scm
  - sphinx-gallery
  - sphinx-inline-tabs
  - xarray
  - zarr>=2.11.0
